### ISSUE TITLE
Latest alpine tag is broken - module 'OpenSSL.crypto' has no attribute 'sign'

### ISSUE THREAD

**Issue by mikehardenize** [GoogleCloudPlatform/cloud-sdk-docker#497]
The latest alpine tag - 503.0.0-alpine is broken:
```
PRODUCTION [root@hyperscan1 hyperscan]# docker run -it --rm -v "$PWD:/app" -w /app --entrypoint bash google/cloud-sdk:503.0.0-alpine
63d3bec7e577:/app# gsutil -o Credentials:gs_service_key_file=.gcp-credentials ls "gs://*OBFUSCATED*"
module 'OpenSSL.crypto' has no attribute 'sign'
63d3bec7e577:/app#
```

Compared to the previous tag which is not broken:

```
PRODUCTION [root@hyperscan1 hyperscan]# docker run -it --rm -v "$PWD:/app" -w /app --entrypoint bash google/cloud-sdk:502.0.0-alpine
ffa5e62f5dec:/app# gsutil -o Credentials:gs_service_key_file=.gcp-credentials ls "gs://*OBFUSCATED*"
gs://*OBFUSCATED*/2024-12-08T08_00_53.360216000/
gs://*OBFUSCATED*/2024-12-09T08_01_01.630430000/
gs://*OBFUSCATED*/2024-12-10T08_01_01.230574000/
ffa5e62f5dec:/app#
```

**Comment by sameer-google** [comment]
The recent release of [pyOpenSSL](https://github.com/pyca/pyopenssl/releases/tag/24.3.0) on 2024-11-28, which introduced support for `Python 3.13` and removed deprecated modules, may be the cause of the issue you're encountering. To mitigate this, you can temporarily resolve the issue by pointing `pyOpenSSL` to version `24.2.1`.

**Comment by mikehardenize** [comment]
I fixed the issue by rolling back to the previous image. Can you please confirm whether or not gsutil is supposed to work within this image? If not, I will either develop my own or go look for one where it is supported.

**Comment by anindyatahsin** [comment]
@mikehardenize As @sameer-google mentioned, the current alpine image is using pyopenssl 24.3.0 which is not compatible with gsutil. We are going to pin the pyopenssl dependency to 24.2.1 in our next release (504.0.0) to fully support `gsutil`. So in `:504.0.0-alpine` you will be able to use gsutil without changing anything. In the interim you can temporarily resolve the issue by pointing pyOpenSSL to version 24.2.1: 

```
apk add --no-cache python3 py3-pip
python3 -m venv /tmp/venv
. /tmp/venv/bin/activate
pip install --upgrade pip
pip install "pyopenssl == 24.2.1"
```

**Comment by anindyatahsin** [comment]
@mikehardenize On a separate note, I was curious, is there any specific reason you use the `:alpine` image? Our most recent debian based docker image `:stable` is the recommended image and is the most secure (all fixable vulnerabilities are resolved within a week) and smallest. We eventually want users to move to the `:stable` image and slowly slowly deprecate the other images. So we were wondering is there any glaring reason to continue using the `:alpine` image instead of the `:stable` image?

**Comment by mikehardenize** [comment]
This system was setup years ago, so I'm not sure what the specific reasoning behind using the alpine image was (even though I set it up). I assume it was related to image size at the time. I'll give stable a try.

**Comment by mikehardenize** [comment]
May I also recommend that you update your build process to test that gsutil and gcloud work within a container before pushing a new image.

**Comment by anindyatahsin** [comment]
@mikehardenize Absolutely. We have an action item on our plate to run periodic integration tests on gcloud docker images.

For Now, we are running manual testing. This version of the image was tested fully a few weeks ago to ensure both gcloud and gsutil works properly within the container. However, due to a recent upgrade in the `pyopenssl` package (released Nov 28th) which is not compatible with `gsutil` component the issue happened.  Since we do not have periodic test for docker images the issue was not caught before the release.

**Comment by anindyatahsin** [comment]
Alpine images is rolled back to version 3.19 in `504.0.0-alpine`. So the issue with `OpenSSL.crypto` should be resolved now. We will upgrade the alpine image to version 3.20 in our next release after testing with gsutil.

Closing the issue for now. Please feel free to reopen if the issue persists.

**Comment by yuzhva** [comment]
Hey hi, guys 👋

In the **alpine** image:
```yaml
image: google/cloud-sdk:alpine
```

We are using **gsutil** to upload static files to the bucket as:
```yaml
- gsutil -m rsync -x "manifest\.json|.*\.map" -r ${APP__ROOT_PATH}/dist/ gs://${CLOUD_BUCKET__NAME}/${APP__STATIC_PATH}/
- gsutil -h "Cache-Control:no-cache" cp ${APP__ROOT_PATH}/dist/manifest.json gs://${CLOUD_BUCKET__NAME}/${APP__STATIC_PATH}/
```

2 hours ago, after the release of `v525.0.0` - our builds became broken, due to the error:
```
Caught non-retryable exception while listing gs://: module 'OpenSSL.crypto' has no attribute 'sign'
```

Are there some changes in the parameters of **gsutil** that have been made?

Or you are still recommending switching to the `:stable` version?

---
Link to issue tracker:
https://issuetracker.google.com/issues/422199553

**Comment by googlyrahman** [comment]
Hi @yuzhva, 

Just wanted to confirm — was it working correctly with gcloud versions ≤ 524.0.0, or is the issue present across all versions?

**Comment by YonathanZetune** [comment]
Hi @yuzhva,

The latest image has been updated with a rollback of the alpine upgrade. Could you confirm if your issue is fixed now?

**Comment by yuzhva** [comment]
@YonathanZetune 

✅ confirmed - the builds are restored
> Operation completed over 81 objects/26.0 MiB.

The `gsutil -m rsync` - uploaded all of the files to the bucket successfully

Thank you guys 🤗

**Comment by googlyrahman** [comment]
Hi @yuzhva,

We've tried to reproduce the error on our end using gcloud-525.0.0 on Alpine 3.22, but everything worked fine. This suggests the build failures might be an environment issue.

You mentioned, `Some time ago, when there was buildx removed from the image, we installed buildx manually - everything worked well.` Could you please tell us what changes you've made manually with steps? This information would help us reproduce the error.



```
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.22.0
PRETTY_NAME="Alpine Linux v3.22"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

/ # gcloud --version
Google Cloud SDK 525.0.0
bq 2.1.17
bundled-python3-unix 3.12.9
core 2025.05.30
gcloud-crc32c 1.0.0
gsutil 5.34


/ # gsutil -h "Cache-Control:no-cache" cp temp/file.txt gs://rahman-bucket/
Copying file://temp/file.txt [Content-Type=text/plain]...
/ [1 files][   11.0 B/   11.0 B]                                                
Operation completed over 1 objects/11.0 B.                                       
/ # gsutil -m rsync -x "manifest\.json|.*\.map" -r temp/ gs://rahman-bucket/dock-te
sting/
Building synchronization state...
Starting synchronization...
Copying file://temp/file.txt [Content-Type=text/plain]...
/ [1/1 files][   11.0 B/   11.0 B] 100% Done                                    
Operation completed over 1 objects/11.0 B.
```

**Comment by yuzhva** [comment]
Hi @googlyrahman 👋

> You mentioned, Some time ago, when there was buildx removed from the image, we installed buildx manually - everything worked well. Could you please tell us what changes you've made manually with steps?


Those are 2 different CI jobs.
In the `525.0.0` image we do not have an issue with the step where the docker image is built.
To fix the previous build where the `buildx` has been removed - we simply started to install it manually:
```
before_script:
    # https://cloud.google.com/sdk/docs/downloads-docker#whats_new_important_updates
    # Warning: To enhance security, we will be removing the docker-buildx dependency
    # from the Google Cloud CLI Docker images (:latest, :alpine, :slim, :emulators, :debian_component_based).
    # Starting with the gcloud version 519.0.0, the docker-buildx dependency has been removed from the :alpine and :debian_component_based images.
    - apk add --no-cache docker-cli-buildx
```

Those are - two Different CI Jobs:

### build docker image change
In the 525.0.0 image, we don't have an issue with the Docker image build step. The fix for the previous build (where buildx was removed) was to install it manually:
```yaml
before_script:
  # https://cloud.google.com/sdk/docs/downloads-docker#whats_new_important_updates
  # Warning: To enhance security, we will be removing the docker-buildx dependency
  # from the Google Cloud CLI Docker images (:latest, :alpine, :slim, :emulators, :debian_component_based).
  # Starting with gcloud version 519.0.0, docker-buildx dependency has been removed from :alpine and :debian_component_based images.
  - apk add --no-cache docker-cli-buildx
```

### deploy - upload static assets to GCloud bucket

After the 525.0.0 release, the error appears in the deploy job. Here's the complete GitLab CI configuration:
```yaml
.deploy:
  image: google/cloud-sdk:alpine
  # Authentication
  before_script:
    - |
      gcloud auth activate-service-account --key-file ${GCLOUD_SERVICE_KEY_FILE}
      gcloud config set project ${GCLOUD_PROJECT_ID}
  # Upload static files
  script:
    - gsutil -m rsync -x "manifest\.json|.*\.map" -r ${WEB_APP__ROOT_PATH}/dist/ gs://${CLOUD_BUCKET__NAME}/${WEB_APP__STATIC_PATH}/
    - gsutil -h "Cache-Control:no-cache" cp ${WEB_APP__ROOT_PATH}/dist/manifest.json gs://${CLOUD_BUCKET__NAME}/${WEB_APP__STATIC_PATH}/
```

**Comment by googlyrahman** [comment]
Thanks @yuzhva for detailed explanation, I'm able to reproduce this now, the issue occurs with service account authentication which is why it wasn't reproducing earlier, as i was doing a user account authentication :P - With that said, We'll investigate this issue further. 

Additionally, I see that you're using `gsutil` commands, do consider moving your workload to `gcloud`, as `gcloud` is recommended CLI for GCS, https://cloud.google.com/storage/docs/gsutil
